### ISSUE TITLE
Support Node v12.x

### ISSUE THREAD

**Issue by alexandr-kazakov** [webdiscus/pug-plugin#50]
1. I have nodejs v12.18.3 
2. Run webpack command
3. Get this error:
<img width="909" alt="Снимок экрана 2022-11-12 в 14 20 44" src="https://user-images.githubusercontent.com/20513262/201471743-16dace92-2218-4b14-ae6e-f572852d75cd.png">

On node v16.x it’s working fine, but I need 12.x.

My webpack.config.js:
```

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const PugPlugin = require('pug-plugin');

module.exports = {
  mode: 'development',
  stats: 'maximal',
  entry: './src/index.ts',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].[contenthash].js',
    clean: true,
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
  },
  devServer: {
    static: {
      directory: path.join(__dirname, 'dist'),
    },
    hot: true,
    port: 3000,
    historyApiFallback: true,
    compress: true,
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        include: path.resolve(__dirname, 'src'),
        use: [
          {
            loader: 'ts-loader',
            options: {
              configFile: path.resolve(__dirname, 'tsconfig.json'),
            },
          },
        ],
        exclude: /(node_modules)/,
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader',
        ],
      },
      {
        test: /\.pug$/,
        loader: PugPlugin.loader,
        exclude: /(node_modules)/,
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.html',
    }),
    new MiniCssExtractPlugin({
      filename: '[name].[contenthash].css',
    }),
  ],
};

```

**Comment by webdiscus** [comment]
Hi @alexandr-kazakov,

Don't use the Pug plugin together with `html-webpack-plugin` and `mini-css-extract-plugin`.
Just one Pug plugin replaces the functionality of both `html-webpack-plugin` and `mini-css-extract-plugin` to make usage of Pug much easy.
Please, see correct use examples of [pug-plugin](https://github.com/webdiscus/pug-plugin).

In your use case of  the Webpack config should be used the [@webdiscus/pug-loader](https://github.com/webdiscus/pug-loader) instead of the `pug-plugin`.

Add the exact version `2.8.2` of `@webdiscus/pug-loader` supported `node 12`  in package.json:
```
"devDependencies": {
  "@webdiscus/pug-loader": "2.8.2"
}
```

In Webpack module rule change  the Pug loader:
```js
     {
        test: /\.pug$/,
        loader: '@webdiscus/pug-loader',
        exclude: /(node_modules)/,
      },
```

You can find last version supported node 12:
- [pug-plugin CHANGELOG](https://github.com/webdiscus/pug-plugin/blob/master/CHANGELOG.md) `v2.9.3`
- [pug-loader CHANGELOG](https://github.com/webdiscus/pug-loader/blob/master/CHANGELOG.md) `v2.8.2`
